import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { Toaster } from "react-hot-toast";
import ThemeProvider from "@/components/shared/ThemeProvider";
// import { ThemeContext } from "@/components/shared/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme='light'
      lang="en"

      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      <Navbar />
      <main data-theme='light'
        className="p-10 ">

        <Toaster
          position="top-center"
          reverseOrder={false}
        />

        <ThemeProvider>


          <body className="min-h-full flex flex-col">{children}</body>
        </ThemeProvider>

      </main>
      <Footer />
    </html>
  );
}
